# Generated by Django 4.2.6 on 2023-10-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymovies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(blank=True),
        ),
    ]
